### ISSUE TITLE
Model-ify ISI Datamart

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#11]
We need to create a "model" that ingests the ISI Datamart, Causemosifies it, and pushes it into the system as an _indicator_.

**Comment by brandomr** [comment]
The more I think about this, I believe that we will have `/indicators` endpoints and we should just add one that fetches the Datamart and ensures that all the indicators from Datamart are up to date. This could be `/indicators/sync_datamart`.

We can call this periodically or Uncharted can.

**Comment by travis-jat** [comment]
This issue was moved to `wm-data` repo and completed [HERE](https://github.com/jataware/wm_data)

In `isi-indicators` folder the ISI datamart is bulk downloaded, schemafied, and uploaded to S3 as a zipped file.
