### ISSUE TITLE
Existing Models falling off of edit model board due to versioning data errors

### ISSUE THREAD

**Issue by mattprintz** [jataware/dojo-deprecated#115]
For example, for the model named "DSSAT For Kenya Maize", the most recent model that exists has `"next_version": "91b38c10-982a-4097-8691-c2124395b68e",` but a version with that id doesn't match. As long as there is not a version of the model with `"next_version": null,` the model will not show up in the edit models page.

**Comment by mattprintz** [comment]
@brandomr Will look in to the prevalence of this and do some cleaning up.

**Comment by brandomr** [comment]
Resolved the issue with DSSAT and Maxhop...checking on others.

**Comment by brandomr** [comment]
I've also removed any obvious test models
