### ISSUE TITLE
Handle DAG failure elegantly

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#15]
If a node in the DAG fails, we need to handle that and update the `run` status in Dojo as `failed`. 

We need to notify Uncharted of the failure (but this may not be possible at this point).

**Comment by brandomr** [comment]
@marshHawk4 I believe this is resolved? If you believe yes, go ahead and close this one.

**Comment by marshHawk4** [comment]
Yes this is done. Basically if every node succeeds then exit_node runs. However if any node fails then the notify_failed_node runs.
