### ISSUE TITLE
AWS S3 script to fix metadata on html files uploaded via DMC

### ISSUE THREAD

**Issue by mattprintz** [jataware/dojo-deprecated#168]
All files uploaded by DMC are being uploaded with metadata of `Content-Type: binary/octet-stream` which is usually fine, but now that HTML files are being embedded in an iframe in Causemos this is causing the html files to be downloaded instead of displaying in the iframe.

As a temporary fix, we want to add a lambda in S3 that will listen for file creation events for files in the the `dmc_results*` folders for any files ending with `.html` or `.htm`.
The lambda should then use the boto3 library to change the `Content-Type` metadata field value on the file to `text/html`.

**Comment by marshHawk4** [comment]
Completed and tested with Matt
