### ISSUE TITLE
Handle ES max hits for indicators and models

### ISSUE THREAD

**Issue by travis-jat** [jataware/dojo-deprecated#19]
Datamart indicators will exceed the 10,000 hit threshold. Need a way to paginate thru all results possibly with `search_after`. See https://www.elastic.co/guide/en/elasticsearch/reference/7.12/paginate-search-results.html

**Comment by brandomr** [comment]
We can also use a [`scan`](https://elasticsearch-py.readthedocs.io/en/v7.12.0/helpers.html#scan) for this. We'll have to check with Uncharted how they want to handle it (e.g. pagination vs everything at once).

**Comment by travis-jat** [comment]
@brandomr updated and merged code to master [HERE](https://github.com/jataware/dojo/blob/74d45c5e1214dd2ec8d05f236e504366d9a3cfdb/api/src/dojo.py#L25-L55) to allow for >10,000 indicators
