### ISSUE TITLE
Uncharted notification configuration

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#27]
We need a way to make the Uncharted notifier endpoints configurable. Currently they are hardcoded in the [DAG](https://github.com/jataware/dojo/blob/master/dmc/dags/model-xform.py) but they should instead be provided as environment variables (probably in the [`docker-compose`](https://github.com/jataware/dojo/blob/master/dmc/docker-compose.yaml#L44-L59)).

**Comment by brandomr** [comment]
Here is the latest endpoints from Uncharted:

```
POST https://causemos.uncharted.software/api/maas/model-runs/{run_id}/run-failed
POST https://causemos.uncharted.software/api/maas/model-runs/{run_id}/post-process
```

**Comment by travis-jat** [comment]
Addressed in the `health_check` repo and merged into master. Set the latest Uncharted endpoints in the dmc/docker-compose.yaml [HERE](https://github.com/jataware/dojo/blob/74d45c5e1214dd2ec8d05f236e504366d9a3cfdb/dmc/docker-compose.yaml#L61-L63) which then, as an env variable is read into the DAG.
