### ISSUE TITLE
Ensure that Dojo schemas match Uncharted Schemas

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#30]
# Overview
Uncharted is in the process of making significant changes to their schemas, which are available [here](https://github.com/uncharted-causemos/docs/tree/model-schemas/datacubes). The location of these schemas may change after [this PR](https://github.com/uncharted-causemos/docs/pull/9) is merged.

This issue requires updating the Dojo schemas, which are available in `api/validation` to ensure full compliance with the Uncharted schemas.

## Schema changes
The current schema changes I am tracking are:

* All timestamps, including `created_at` must be converted to epoch millis (e.g. `1234567890000`)
* `period` is now in epoch millis
* `concepts` are now `ontologies`
* each output now requires `is_primary`: “Does this variable represent data based on the primary time and location columns”
* note that temporal resolutions have fixed enum

## Testing
This may require (likely does!) updates to all our examples. These should be tested by passing them into Dojo, but then also checking their schemas against the actual JSON schema created by Uncharted. If it is acceptable to Dojo but unacceptable by the Uncharted schema standards, we have a problem (and vice versa).

**Comment by travis-jat** [comment]
Leveraged `codegen` functionality in pydantic to autobuild pydantic schemas via Uncharted's json schemas; see issue #36 for follow on work
