### ISSUE TITLE
New schema causes rehydration to fail

### ISSUE THREAD

**Issue by travis-jat** [jataware/dojo-deprecated#33]
The updated schema from [HERE ](https://github.com/uncharted-causemos/docs/blob/8a1eeed86358cc531a61409a8fb23247d5f02e92/datacubes/model-run.schema.json#L133-L141) requires the parameter value to be a string to initiate/kick off a model run.

The original schema allowed for any value as seen [HERE](https://github.com/jataware/dojo/blob/1a5a6f706a9415cf8e837643bd5846e40c4b69b6/api/validation/RunSchema.py#L21-L24). This new requirement to strictly be a string causes the rehydration task to fail [HERE](https://github.com/jataware/dojo/blob/1a5a6f706a9415cf8e837643bd5846e40c4b69b6/dmc/dags/model-xform.py#L86-L90)

Two Options: 
1. negotiate a change with Uncharted to allow `Any` type as a parameter value
2. Update the rehydration code in the dag to account for string type; which may be tricky to get that actual data type.

**Comment by brandomr** [comment]
@travis-jat I just opened an [issue on the Uncharted schemas](https://github.com/uncharted-causemos/docs/issues/10). For the time being, let's go ahead and set type to `Any` for `parameter.value` in the run schema [like we have it currently](https://github.com/jataware/dojo/blob/master/api/validation/RunSchema.py#L21). 

> Note: this didn't seem to be a problem for them in the hackathon so I expect they will implement our suggestion.

**Comment by travis-jat** [comment]
Addressed in `schema_updates` branch and merged into master. Testing shows proper config file rehydration after schema change negotiation with Uncharted and additional "data_type" dict in the DAG to capture parameter type.
