### ISSUE TITLE
Output directory should be stored in dojo output file, not directive

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#41]
@travis-jat @hartleybrody we may have to rethink storing the `output_directory` as part of the model directive. We capture the directive at the time the model is run, but won’t ultimately know where the output is stored until the user annotates the output file (which we haven’t integrated yet). 

Shorthand currently just stuffs `/results` into the `output_directory` key for the directive but this is not correct. Far better for the user to do something like `output some_output.csv` in Phantom, have the Spacetag full screen modal pop up, and we know the path to the output file then. At that point we _could_ update the `directive` which we've already stored, but probably better to just store that info with the output file itself in Dojo. Not sure the implications, this could be a hurdle in DMC.

The output annotation integration will be with Spacetag (FYI @BecketTrotter)

**Comment by hartleybrody** [comment]
Not sure how much I know/can help about this issue, but let me know if I should change shorthand to stop setting [`"output_directory": "/results"`](https://github.com/jataware/shorthand/blob/master/views.py#L107) when saving directives.

**Comment by brandomr** [comment]
Resolved by #49
