### ISSUE TITLE
UAZ Ontologies for `qualifier_outputs`

### ISSUE THREAD

**Issue by travis-jat** [jataware/dojo-deprecated#44]
Awaiting UAZ response to request for updating to latest Uncharted schema.

Currently UAZ API does not adhere to Uncharted's schema; specifically `qualifier_outputs` are not accounted for and no ontologies are returned, albeit they should be. 

Once UAZ makes their changes, `api/src/indicators.py` will need to be updated to include the ontology object(s) in the indicator's `qualifier_outputs` list prior to creating indicator in Dojo and writing to elasticsearch.

**Comment by brandomr** [comment]
Resolved by #64
