### ISSUE TITLE
Register SuperMaaS models

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#7]
Examine whether/how we could bulk register the models that exist in SuperMaaS.

We'd need to create metadata specs for them like we have for MaxHop (see [MaxHop metadata](https://github.com/jataware/dojo/blob/master/api/examples/maxhop.json)). We'd also need to specify their config and command templates like we do for [MaxHop here](https://github.com/jataware/dojo/blob/master/api/examples/Examples.py).

Finally, we'd need to annotate their outputs with SpaceTag to generate a mapper such as [this one](https://github.com/jataware/dojo/blob/master/api/examples/mapper.json) we have for MaxHop.

**Comment by marshHawk4** [comment]
Question for meeting at 10. Our metadata file is basically the combination of the parameters.json and metadata.json files that are used in SuperMaaS?

**Comment by brandomr** [comment]
It's quite similar, but we also need the templated execution command and any templated config files plus where to mount them. It may be possible to avoid this for SuperMaaS models to some extent since the containers have a lot of execution logic baked in. I'm not sure the best approach here really.
