### ISSUE TITLE
Scrape phantom images from Dockerhub

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#77]
This https://github.com/jataware/dojo/blob/dev/api/src/phantom.py#L36-L45 should be replaced with something that fetches off Docker Hub.

Specifically from the [jataware/dojo-publish](https://hub.docker.com/r/jataware/dojo-publish/tags?page=1&ordering=last_updated) Docker Hub repo

**Comment by GoogleSheets** [comment]
@brandomr It looks like there is a docker hub REST [endpoint](https://hub.docker.com/v2/namespaces/jataware/repositories/dojo-publish/images) that will return tags, but it returns a 401 with the message _"user does not have access to this namespace"_ (although the [images-summary](https://hub.docker.com/v2/namespaces/jataware/repositories/dojo-publish/images-summary) endpoint works) and the [docs](https://docs.docker.com/docker-hub/api/latest/#operation/GetNamespacesRepositoriesImages) give two possible errors:
```
401 Unauthorized - user does not have read access to the namespace
403 Forbidden - this API is only available to users on Pro or Team plans.
```
Does Jataware have an upgraded plan? If so, we could probably try those credentials. Otherwise, we'll need to scrape the url.

**Comment by GoogleSheets** [comment]
@brandomr Ok, that works. Here is an example of the API response:
```
{
    "count": 79,
    "next": "https://hub.docker.com/v2/namespaces/jataware/repositories/dojo-publish/images?page=2&page_size+=100&status=active",
    "previous": null,
    "results": [
        {
            "namespace": "jataware",
            "repository": "dojo-publish",
            "digest": "sha256:81ae08c9a8093e0c0c10313b844aa70e1f5be6c582b1c1a41fc073a37df35528",
            "tags": [
                {
                    "tag": "GoogleTrends-latest",
                    "is_current": true
                }
            ],
            "last_pushed": "2021-07-15T01:16:32.454626Z",
            "last_pulled": "2021-07-21T14:58:42.765245Z",
            "status": "active"
        },
        {
            "namespace": "jataware",
            "repository": "dojo-publish",
            "digest": "sha256:ee4e2f6c8eb911c5e29eabf00db72e0a56f675b8894f8d52ea02cc71339c5241",
            "tags": [
                {
                    "tag": "asdf-latest",
                    "is_current": false
                }
            ],
            "last_pushed": "2021-07-29T15:40:01.243148Z",
            "last_pulled": "2021-07-29T15:40:01.47939Z",
            "status": "active"
        },
```

It looks like the format to be returned by `get_base_images` is:
```
{
  "sort_order": 0,
  "display_name": "string",
  "image": "string"
}
```

1. What are `display_name` `image`, and `sort_order` here? (guessing image=digest and display_name=tag)
2. Does `add_base_image() `also need to be modified here, and does that mean putting images in dockerhub?
3. I missed the url for the actual UI with the drop down; it might be helpful to fire that up.

**Comment by brandomr** [comment]
@GoogleSheets I'm not sure what `sort_order` is here but I think:

1. `display_name` would be the tag stripped of `-latest`. So for example `DSSATForKenyaMaize-latest` would become `DSSATForKenyaMaize` (you can do `.replace('-latest','')` since not all will have that
2. `image` is the full name so `jataware/dojo-publish:DSSATForKenyaMaize-latest` per the above example

@GoogleSheets `add_base_image()` can be removed if we are able to pull the image tags from Dockerhub. We can discuss tomorrow how to actually test this; it will be a bit tricky, but if you have a PR up on Dojo let me know and I can walk you through testing.

@scotthaleen what is `sort_order` in this context?

**Comment by GoogleSheets** [comment]
@brandomr Here is the PR: https://github.com/jataware/dojo/pull/79
