### ISSUE TITLE
Register Pythia DSSAT

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#8]
Register Pythia/DSSAT like we have done for MaxHop.

**Comment by brandomr** [comment]
https://github.com/DSSAT/pythia

**Comment by brandomr** [comment]
@travis-jat good news is that this integration is working after @marshHawk4's config file rehydration work! 

@travis-jat when you have a chance, can you clean up the [Pythia example directory](https://github.com/jataware/dojo/tree/master/api/examples/pythia) so that it only has the necessary files and add a short README explaining each file and how to set up the model? Mostly I'm confused by `pythia` vs `pythia_short`.

**Comment by travis-jat** [comment]
Addressed schema and rehydration issues and merged into master that allow registration of pythia model through dojo.dev.com
