### ISSUE TITLE
DMC model run logs should be pared down

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#82]
and contain only relevant info (e.g. the model task logs) and possibly the mixmasta logs. If there are errors this should somehow be highlighted.

**Comment by scotthaleen** [comment]
You can have multiple handlers to a logger and write errors to an error.log file rather than everything to stdout.

**Comment by brandomr** [comment]
This should really be called "DMC model run logs"; I'll update the title. The issue is that the logging from each model depends on what the modeler wrote and some of them are ridiculously verbose, others are practically nothing.
