### ISSUE TITLE
Rehydrate config(s) and mount them to model container

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo-deprecated#9]
Currently there is no support in DMC for models that require templated/mounted config files.

The SpaceTag mapper is pulled in by the [DAG here](https://github.com/jataware/dojo/blob/master/dmc/dags/model-xform.py#L71-L79) in a specific node called `mapper_node`. 

We need to extend the DAG to have a new node which gets the config(s) for the model and "rehydrates" them. Rehydrating a config means injecting the appropriate parameter values into it based no the user parameter selections. This should precede model execution.

Some of this _could_ theoretically be handled by Dojo. In that case we'd store the rehydrated config(s) somewhere in S3 and put their paths in the `run` attributes. Then DMC would need to download them and mount them to the model execution container at the appropriate path.

**Comment by hartleybrody** [comment]
I'm not 100% in the loop on what this needs, but wonder if it is complete now that this has been merged?

https://github.com/jataware/dojo/pull/22
